# Generated by Django 5.2.7 on 2026-04-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('patient', 'Patient'), ('accountant', 'Accountant'), ('teacher', 'Teacher')], default='patient', max_length=20),
        ),
    ]
