# Generated by Django 5.2.7 on 2026-04-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appointment_is_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('accountant', 'Accountant'), ('teacher', 'Teacher')], default='patient', max_length=20),
        ),
    ]
